[segments]
MSH = "msh.toml"
EVN = "evn.toml"
PID = "pid.toml"
PV1 = "pv1.toml"

[[message.adt_a01]]
name = "MSH"
required = true
[[message.adt_a01]]
name = "EVN"
[[message.adt_a01]]
name = "PID"
required = true
[[message.adt_a01]]
name = "PV1"
required = true
